name: vg_deconstruct
description: Deconstruct snarls present in a variation graph in GFA format to variants in VCF format
keywords:
  - vcf
  - gfa
  - graph
  - pangenome graph
  - variation graph
  - graph projection to vcf
tools:
  - vg:
    description: |
      Variation graph data structures, interchange formats, alignment, genotyping,
      and variant calling methods.
    homepage: https://github.com/vgteam/vg
    documentation: https://github.com/vgteam/vg/wiki
    licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - gfa:
      type: file
      description: Variation graph in GFA format
      pattern: "*.{gfa}"
  - vcf_spec:
      type: value
      description: tab-delimited VCF specification, each specification is delimited by a ":" and a specification must consist of "ref,delim" and optionally a "pop_length"
      pattern: "*.{gfa}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file(s)
      description: Variants in VCF format
      pattern: "*.{vcf}"
  - stats:
      type: file(s)
      description: bcftools statistics of VCF file(s)
      pattern: "*.{vcf}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@subwaystation"
