name: "split_approx_mappings_in_chunks"
description: Split approximate mappings of WFMASH_MAP into chunks so that we can parallelize WFMASH_ALIGN across nodes of a cluster.
keywords:
  - alignment
  - pangenome graph
  - mapping
  - graph construction
  - splitting
tools:
  - "pggb":
      description: "PanGenome Graph Builder"
      homepage: "https://github.com/pangenome/pggb"
      documentation: "https://pggb.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/pangenome/paggb"
      licence: "['MIT']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - paf:
      type: file
      description: Approximate alignments in PAF format.
      pattern: "*.{paf}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - pafs:
      type: files
      description: PAF files containing the same information as the input PAF, but splitted into equal problem sizes.
      pattern: "*.{paf}"

authors:
  - "@subwaystation"
